name: "üêç Linter"

on:
  pull_request:
    branches: [master]
    paths:
      - "pycrosskit/**/*.py"

  push:
    branches: [master]
    paths-ignore:
      - "pycrosskit/**/*.py"

env:
  PROJECT_FOLDER: "pycrosskit"
  PYTHON_VERSION: 3.6


jobs:
  lint-ubuntu:
    runs-on: ubuntu-20.04

    steps:
      - name: Get source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install requirements
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U -r requirements.txt
          python -m pip install -U -e .[dev]

      - name: Lint with flake8
        run: |
          flake8 ${{ env.PROJECT_FOLDER }} --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 ${{ env.PROJECT_FOLDER }} --count --exit-zero --statistics
